variables:
  global_variable: value # this is available to all jobs

jobs:
  - job: job1
    pool:
      vmImage: "ubuntu-16.04"
    variables:
      job_variable1: value1 # this is only available in job1
    steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable1)
      - bash: echo $JOB_VARIABLE1 # variables are available in the script environment too

  - job: job2
    pool:
      vmImage: "ubuntu-16.04"
    variables:
      job_variable2: value2 # this is only available in job2
    steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable2)
      - bash: echo $GLOBAL_VARIABLE
