name: dependency jobs

pool:
  name: aci-pool

stages:
- stage: experiment

  jobs: 
  - job: jobone
    steps:    
    - bash: sleep 30s
    - bash: |
        now=$(date)
        echo 'finishing jobone at: ' $now
  
  - job: jobtwo
    dependsOn: jobone
    steps: 
    - bash: |
        now=$(date)
        echo 'finishing jobtwo at: ' $now