name: variables scopes and jobs
variables:
  globalvar: current-value # this is available to all jobs
  changingvar: original-value  

stages:
- stage: stage_deploy
  displayName: Production
  jobs: 
  - job: job_deploy_infrastructure
    displayName: Deploy Some Infrastructure
    steps:
    - bash: |
        SOMEVALUE="bleh"
        echo "##vso[task.setvariable variable=someName;isOutput=true;]$SOMEVALUE"
        echo "variable value is $(someName)"
  - job: job_deploy_code
    displayName: Deploy Some Code
    dependsOn: ['job_deploy_infrastructure']
    variables: 
      someName: $[ dependencies.job_deploy_infrastructure.outputs['someName'] ]
    steps: 
    - bash: |
        "the variable value is $(someName)"
